version: "3.8"

services:
  nginx-port1:
    image: nginx:latest
    container_name: nginx-port1
    # Long syntax
    ports:
      - protocol: tcp
        published: 8080
        target: 80
    
  nginx-port2:
    image: nginx:latest
    container_name: nginx-port2
    # Short syntax
    ports:
      - "8081:80"